; generated by PrusaSlicer 2.6.0-alpha4+win64 on 2023-02-21 at 12:21:10 UTC


;
; thumbnail begin 16x16 556
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABZ0lEQVR4AY2TyU7DQAyG5624dW/2pE
; mbBAnaFLhx49Yji1R4Lp7M9DNylKiQ9mBlxvH/zYwXNxqNZDwey2Qykel0KrPZTObzuVoURZJlmSwW
; C93zjxhi0aB1bExE4HK5FN/3JU1TBQRBoOswDPVfF4bWEex5npoF53kuSZL0DP9qtVIQscAAOTZxHG
; vAZrOR9XqtgUCKolBjjY/nsAfIYWidnVpVlZRlqQBArPGZHx9iQAZF63AgwvFY5/LaxPLRRHLch/K5
; j9RYH5tAvhpfHqrf23EbtM4WQA73sXw/3wzay13aPpOnOEsaVzxskysAmcaiQdsD8PMSgEN6gO4TuN
; 5FwOmZ9gS0zkoDsSkzOe68U8LCNonvu0DetpivCX66Ldob89UykgyoVvehMvKt61pP1zJaB9JM1jz/
; NZIBiMUUQDvSlgbiNlairlnSrANNczZMOJkPRHYSQBOeDdPQONuM2P6vcf4BBIn2jeOQK0gAAAAASU
; VORK5CYII=
; thumbnail end
;

;
; thumbnail begin 220x124 9240
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAa2UlEQVR4Ae2d93MVx5bH71+09YKfve
; 95Tc4gkATKIBACGUwOBgEm54xJwmDAmGw/V61db2trt9a1tX9Z7/u0q+W5owmdZ+ZyfzglkO6d0N2f
; Oed8+3RPa968eWL+/Pm5tmDBglxbuHBhpi1ZskSsWbNGbNmyRSxatKjNFi9enGl8J8uWLl2aacuWLc
; u05cuX59qKFStybeXKlaW2atUqaWvXrhVffPGF/Kl+l7bVq1c32vLuq6+vT4yMjIjNmzfP/k6n7Yra
; vqjP8vo5b1zkjaO8cZcen4ODg9L4W974LmKiiCVYa/mGLQ3X8ePHxfj4eO5N1x205GBbt26dOHv2rN
; i9e3fboLQd1DyUqjBXCPk34F26dEls2LChrY2aCl5/f7/4+uuvRU9PT9sY9g1dKxRsyhikjx8/Fvv3
; 79eCLQZoJpAlvdrMzIy4fPlyI6CKAeOOHTvE27dv5c+sNrOFLzR46XE4NDQknj17JjZu3Jg5hn1C1w
; oJW/KmaJSJiYnCp48JbL69WV4IhRFCce08/ULCxfFDWEgIe3t7xcDAgNi5c2dhG/r2ej68HbZ161Z5
; j0Vhpk/oWrqwmYCWl6txg4cPHxb79u2TjebTq9mAVjRAMMIlwoyxsTEvgIUCKjaQWe1AJHPq1CkxOT
; lZ2q6+wHPxdlNTU+LKlSvyODq5nS14hcCFhg2jYbnRa9euBQXN1pupQYRXe//+vdizZ48VZL5gIJQ1
; sdgQJtuGNnv9+rUEr0x8sfV6ruAxBhG8SA94SBTldiGga8WELWk0FO6cTvEZPtqAln5i8/RDqdIdeD
; FA8m2hIOTY69evl8JSOgT3BZ5LmLlr1y55XF1BxTd0LV+wmcj9yQYgXDt9+rTsrBBeTcebKUPqvnPn
; jlTgfEFWNVihQCxrH7wHYsr09HSu2qkLn6u34/dcB2YqqPjM6yRwoWAzEUZoCJTMJHShQMtL/nki//
; jjj2LTpk3WgNkOcgZnDAsJYVabIbXfvXtX3Lt3r3SqIRR4/JvpC4zjukwf+ICuFQu2slyNhsHbIdG6
; hI+moDEwDh48KAdWSMhiQRUaRlP4+D/iE2IKP0OBlzVm+D4PUr6jk9vFgK5VB9iS0CEz37hxQ+ZQpn
; maCWgMhL1798onX9YgqRIw2sCHVQ1gOrfjgXru3Dn5bxPwTPM7zs0YAnKTKYQY0LXqBJuy7du3ixcv
; XojR0VFrr1bk0TBAe/r0qQx7fEBWBVAxgfQBH8c5ceKEVH8RVorm+Gy9Hef65ptvZNSS9Hx1ga5VNW
; x54SMNTKegGPoIH5PJPGGGCiFtQWsaXL4hdAGP6IVyP2pt8+b2bMJM0hGEL76rK6rEhq4VCzZbBZLG
; vHjx4uyEqqlXUx3KYKIOkhKzkJDZDnSU0ZAWEkAb+Pgb18V8LJUqpuAlYQO0+/fvywe0rZIZC7qWb9
; hsQsgi2DCeiN99952cQzEFTeUPT548EdevX/cOWp2gigGjb/CINn744QeZRhRVs+SBR15IHSQP5Lww
; 0xa6LPBcoWvVATYdYYTGpeOo/DCBjeqHzz//XA4IE9B8QOYCAbmli8UA0Aa+rD7AMzEdQz+ZQEe6oZ
; RPGyWzCuhaTYEtaV999ZWsyaSz8kAjTCHMoALcB2i+AXMFKiaQLvDpgqfanrIwVVCcBx6F0rdu3ZKf
; L8rt6ghdq2mwYXQwDa4k/TRsxPTv3r0TBw4cCA5aE+DyCWFo8HhAvnnzRhw9ejQTOqZyKJKgj3UElb
; pB14oBm0m+VgRb+klHB5PXJed8iOVRwNIhpE/QQgBGWBXSQgAYCjw+R95O3yo1GSOd4LxluZ3O9IEv
; BdMUulzgfKmRoWBLejVCjNu3b8snX1644gqaL8hCgxUKRFv4TMBL95t6oFIadubMmdkHq46gEgo6W/
; WyDTgd7xYLNh0VMl2CxXKLX3/9VTx//lx2fizQYgCGKGBiMQCMCR4P0l9++UVCl65esZksjwVdnpdr
; hYJNJ2fzARvzaggkdAYdjnJFhUoo0HwDZgqUq/kGMBR4XCveTf2NnA0xhVAzNHQ6OZ0tdC0feVts2I
; CLeP7q1auZ4SPAIaoo8EKDVle4fEMYGjz6ivNQB0n/pr0dxyNHZzlXMrerC3Q6oWUrhkhiClvZ3BrS
; MeEjgyUvV6PDqMdkfqcq0GwGP97ap4UAMBR4fI5J7GPHjsm/ZYWY/J7+R4U2rVBxhc6HiNIyCSWrho
; 3GRxZO5mlFuRqdg5djIWQebKag+YLMN1ihQLSFzwQ8+oYayG3bts3+vyy3o8KEKQS+V3foMoELIZL4
; gk091agAt1EgGRg3b96U+V0ZbDagNQEwHwD6Ai/ZB0Dz6NEjCZCpoMJnuC72yOFnVdCZ5HMtX3lbKN
; ho1AcPHsicrAy2olyNubmXL1/KCpVYoJkOerXrr2/zDZ8v8PBOr169kuJIWW5XNH1A1MOSH1WhUgfo
; 8kLLlk0oGUIkyYINZUqFgy6wJT0ax6QCJTkITEDzBVkouHxDaAtfGXTMnVLnaiKoFEHH8bkvxouOkF
; KFiCKBq2MoSUfi0fBKOnWQurAljSU/R44ckefSgc0VsqoB8wGgKXhZ0LE6gH1OOF5RbmcDHb/juyxy
; Za1dHUPLlqt38w0bnU+YQeiXtUC0DDZdYWR4eFiGqkwt2Ho1n5DheUOaT/hsvR0bABPW8yA1EVRMoG
; PMoExTj8l7LeoWWrbqBBvbiZM8qzmWULClvRkDgUHpA7S6AOYLQF/gEU3wHRNBxQU6vsf5mB5Kh5hV
; QhcNuCLYUKrwNnRM3kY+PmArytUYEKw+wPOFAK1qwFwBtA01T548KV+AokDUEVR8QZfcUuPQoUPa0E
; UBrirvxqJDVvwm97eIDZvyZuR1TLwyAH2AZjrogT2E+YTPBDzkemoguQYTQcU3dJyTqQd0AeXtqvJy
; XoCzhU1NYhdtURcDtmT4qMIQJOsi2FxBCwWXTwhtwKPN+Dvr2ZIQmqqYvqHj31wX6ijHdoXOCbiYoa
; RaTsPmMVm79YaGTVcUYU6HFeN4Xl+gVQ2ZLXy64CHz87YhBC/VjkMD68XYQL+00Q19peD5hi49vvg8
; KYzaXj92aNkynQZwCSV5qhDTsyFQMl+z8W6usA1u6BcTg71i+9A6sWP4d9uJjfxmt4/tEX9/eE0cnR
; gQ+0fXigNjv9nRjWtmbRrb1CPt9PjqTDu/ebW4tHnVHLu6ZaW4sWX5HLs5sULc27os02a2LhWPJ5fM
; saeTi8V32xalbKG0t9vnZ9pPU59l2r9P/Zv4x+efZtp/7/hrpv3fzk+0bNdwj3fodL1cskSQ9XWo4R
; zLV2ipM03Q8undimDjxtNvVPEZSpp6tn0ja7QHSdf82b6RHq05uzLobEPLpGKJVyZ1QBnXhc7Vy7VC
; ezdulonIL7/8snBdW0zYfgOup1EDtZOA050o9wlderypcaiqVBDMOEdoL9cK7d0ePnwoV+3qwpYGLg
; RsdPgXQ13gqrBDo2uMqlNcoCsLLZPjUdVjMikf0su1Qng3LpgGpTq/bG2bz7zNRI0kX2vSQO0UOzK2
; unCSvEy99JnPpccl30ckQjBzEVC0gPPl3WgUlsKoJ0V6krvKUDLZ0V3g6gGcDnQxQks1TaDAY1t8cj
; vfXs4KuDzvxs1Tw0a+VrQKwId3c4FNet/h3kYN1E6x4xtXZ06S+4TOxcupcavqMalQ8Tkvlwmczbwb
; Ho35jfSEYgzvZgqbnGcb6mvUQO0UO7lxVW45mAl0Ib1cUllnrlG908JlXq4NOBfvxsTpzMyMvOmseT
; cb7xYylFTVI13gqgUutJczEVDKVhSorRiZ1nL1ci0XsYQ5DN6LTTVGWYGyL+/mAzY5/zLU36iB2il2
; dtPKwvpLF+hCeDklnnAuXvR44cKFtvDSVDxp2YaTlGcpr5ZXVRLbu+nChm0cXN+ogdopdmF8RWnRcx
; F0VXi55PjmelhGxrlswsqWSTjJSXmPF/sG6pRx+QbOl3frAledXXQEzsXLuQKnjM+jV0xPT8v/m4SV
; RsBRlMpej9y0yXo323AylHeThbaDA40aqJ1iVzYvz1xtEMrL+Qwrk2oln6EeEx44lhfgkmEkS1Y4sG
; 6Rcuhw0sW7qar/Jg3UTrHrm5c5A+eiWPrycooDNZbweDp5XKvIu3EiVkLj2UxXBegAF2reTQe2LnDV
; AmcKXah5OVfgMP7ONZw/f14es8jL5QLHgagYoQ4yDVvV4aQP74b9746PGzVYP2TgXLxcqLAybUSB7F
; 5AhYoRcFwIWx9wEt3aSR3gqggni1Zqm6zj6pofuzuxtHDleJ3CShPgFCccn2tjqqwUOE7Ohi982Hbd
; W2x10ta7dYGrP3Au4knMPC5reoDP8y56iqEzgeNCWIlNHaRJsXLV+VsXuC5wdcjjsubjEFJev34td/
; puAw4K2Y+CL5quDigCrur8rWzjn/+Y6gIX2x5OLCndkKiueZwpcEp45FooDeP/LTZ94QJsVgf4Ekx8
; 5W8m3g1jj44mDdZOsG+2LjYCzkSttM3jfAknRRPgqmikRT2k7XKcGMCFCie7wDUTuBB5XAzgYIxraL
; msf4uhUIYEjh2qmjRYO8G+m1xYO+B8K5VFFSe1Ay6UYJK1p2IXuHoAl4YuhnDSEcD5mBKIBRxCURe4
; aoDL2ly2rsAVCScdD5xPhZJOf7etC1xse7ltQSlwMZTKLnAVAPdm2/xGDdZOMNq8C1wXuK51gesCFx
; q4F5Nd4GLbD9vndYHrRNFEBzgS+CYN1k4whCqfwH3QoknTpgW6wFUDXHda4AOd+H62dUGjBmunAvdB
; TXxz0A8VOMqMmjRYO8Eop/uggXv58qU8YRNrKV2Ll7vANQ+4IsGkzrWU2JMnT0SLD7I0h73U84Dr1O
; U5MxOLGjVYP0TgQiiUMZfnYFzb6Ojo7zkcv+Si7ty5IxvAF3AhFqCaAFcGHYshmzRYO8FY9OsrnAwB
; nK5CqQMc18A2elx3pmjCCtXvv/++8i0WQimVXeA6C7gqpwTKgONYakOhwk2E+DInYhOhJggnLnncnc
; 1LGjVYP3TgQuRvIQQT1phyL2nBpHSbPHaWVeCFFk6qCCvZsq1Jg7VTrK7hpCtwRIavXr2Sf89SKAuB
; w7ipx48fy42F6iSc+Aoru8A1FzjbcDKUYMJritmEi/PlTQmUApeEjP0YYuZxLmGlLnRd4KoDzqd3Cx
; FOmgA3OTkpP182BzcHuLx3Cyjw8HSnTp3qmLCSN7k0aaB2im0c2tAR4eTRo0fFrVu3CqcElpq8zCMN
; HRd58eJFwU5fRR6uirDSBroucBUBN7g+mHeLBRybvN69e1f+X6fCxAo45emUiskNxAwrfXu5LnDNB6
; 4ItlDhJHtM6kx4ZwLn8srh8fFxcf369VnwmublTm/sAleF8brnJnq3Bw8eiP3792tXmKS50nrHd1Fd
; JRdz8OBBOVnORVfh5UwVyyR0vOC9SQO1U2zrUF8mbD6VSZ/ejZ+83xsNw6Zg2Qm4rOkBLpI5CGoydY
; Grg5frAlcv4Org3dLAcV7SJ9P6yULgXMLKpFpJI8zMzIjh4eFKvZwudNNjXeCqsKnh3qCw+fBuXAOR
; G+WOOtUlOuGkNnAmxcwTExNytp2fPr2cq4CSBd3RsTWNGqidYjuG1xXC5lMosfFunOPdu3cyarNZHa
; AFXBo6E+DS0HEjzHMxIVhnL3dkbHWjBuqHAlyV3g0hEK9mUjtZBlySsVzgTMSTvMoTbgIVc8eOHVG8
; nCl0h0a7Hq4K2z2yNgpsJt6NiOzNmzfyGGWVJTZiiTNwugXNeLqnT5+KQ4cOWXm5kNDtG+lp1EDtFK
; PdY8NW5N0oWyRf4xpMVwY4ARfCyylPRwPs3bt39maLvJypamkLXRc4O/ufqY8z7b+2/0X85+RHc+wf
; W/8sfpn43XYPr3GGzUSVLPJuu3btmvVqOnWTLt7NGThdL6eMGz19+rS00KGlDnQ7h3rE38f/KH7Y9A
; fxdizbvh/+F/Fi5A/ixeif2uzZyB/Ft0N/EI9HPmqzR8N/Fg8G/yTuD30k7g9/PGtfD/1F3B74zW4O
; /WubXR/8RFzZ8Im4PPi3Nrsw8Ddxbv1fxdkNn4ozA5+12Yn+T6Ud3zC/zb7s+0zaofULE7ZA7O9bIP
; b2zhe7+xe12Re9i8Tn6xaKqd7FYqpvidje+7tt6VkkbXzdst9t7dJZ27RuudjYu0LaeP9qcf/yGfHl
; zq1irG+NGO1dLW2kd9WsDfeuEUN9//Ru/X1GsIUIJY8cOSInsnXrJn14Nwnc4sWLhU/oymosaayrV6
; +KmzdvOnk5H9DR8QP9vWJwfZ+0gfX9s+Hm1NSUjOl37tyZuydKemPZImOqxMWY4ywy1+OXXX/Rvav2
; YeElWwocPnxYa1I7BmxZoSR1kExf8f8i2Hwpk8pgzTtwOtBx0zQEg5oGqxK6LDFl3759Uq1K1176AM
; 8HfL5M51p1QEsbx6YN6wYbtmfPnlnwTGDzClxo6IpqLFEwb9y4IRuzaugo3bl3796cKohQ4MUG0OSa
; bEBLe7Rr167J9IHvVA3b/fv3xfT0tPESHJ+wFQIXSkBJQ0fDEE8/e/aszdvFgC4J3vHjx8W3334r52
; CK6i9NwTOFzweItucru4+iNshqM455+/Ztcf78+VzQYsD26NEj2b+6sPkWSjKBqyq0TILHzD77Y8b2
; dOQcDI6yomdX8FzgC2U612wKWlYISRvH9mwqFy+qlYwVSmYCVzV0NBIbZj58+FAKAWXA6UCXN2VAZ5
; w7d05aXohpC54ufFUAqHtdZfenC1rSs7GyhBXS9K2N9J8FWxZwnA/xhge47tKbGLB5Ac5Vtcwq+2Ii
; EoUQ4SIUdKzWJcdg8JTldi7gmcDnC0bb8+nciw1oSSOn44HKsULAxud++uknsW3bttKVAK6qpBfgqv
; ZyCjoaj45Elk83qk14qaBjYKGgqSdsVk5hA15o+EKZC2QmoCVDSH6iFhLN2MKWNSYozyIH11l2U4V3
; k8AtWrSoFLiqoMOUN0LNNIUuCR6DCwWSygJTQSUEeFVAaHpdNqCZCCMAwsJO5u/yQNOBjeO8f/++Te
; muGrYs4GBNAqcDXfoEMaEj5icmJwewgY7BgwKJGqqeqLrQuYBnC6ALjC7n0rkXU9DKhBEiGPZzxDPZ
; wMZ+kG/fvpX3XhVsOt5NcZYLXIh8zgU6BRf1mCZ5HXkgOWFe6OILvBjwhTBXyGxBS5vqJ5N8jZXYHF
; N39bYP2GxDyTnA+YIufcE+oVPgsTcmVgQdHUi4Qp5gKqiUgecLvpggml6PLWR5oOnkalwnYT9eLw1d
; sq8pUGBH8J6enqCw+crbkoy1ARcrn7OBLgkenUp1yqVLlzK9HXIwyy2ST8wy6EKBZwNfVaZzL75Ay8
; vXSB8I/9mKLsurHTt2bA5sWWPFFLaQeZsRcHWFTnk7Qsxkx9BRDJ70E9IHeD7gqwuEJtdqA5kpaOkI
; hfOiZPI31bdqeVeRV6sTbFrA2YaWVUGH7d69Wzx//lyWEdGhuvN1ocAzhS8kiLbXUXZ/vkAry9fYMQ
; AF8uTJk7WBzSaUnAVu4cKFou7QleV1rCb/+eefBe8rTz4RY4CnA58LgLFM5x7K2sEnaKrvWLNGv164
; cMEoX6sjbLAmgWsydExiq3ieTqR2jmoLmwqVMvB8wVcliKbXZwuZC2iqYoTIJZk+qNXZTYWtDThd6H
; TyOV/q5cqCtXQnTpzIDDPUvB0KJZXzZdDZgqcDnw2ALlD6OJfOPZW1iwloadi4DwQvHpxZISRF0Jcv
; X5bXoRNC+lIjbUWSJGxzgGsKdMT1V65cmfO0Sz4NmaMhFEFq1vF2LuDpwucLQJ+me906beACGsb18F
; 7sNGxpj8bDljc4pYGrO2zawMWGLi/EpJNQIU1UTJb7UI2gU49ZBp5v+GLBaHs9LpCZgIYxb0qJlokw
; QrkfHtE2hAwNmxZwLvlcKOjoPPZAoYF1crs0eHyf5Jsnpwl4PuBzATC26d6PDWR5oFFHiQoJOKYKJD
; Y2NiYny0kfqoJN17tJ4BYsWCCqgE5XTKGhnzx5IpVI9STThS4JHhUnTB0wt5PV8S7gmcBXBxBtrrXs
; /k1BU0XH1EECSxFoZcIIBQ7sfcp12ogjsWCDNQlcnaBLgkf+RTiYF5+bejs6mQFHB2WtKPcFny2Arm
; D6PKfOPdpAphRlUgP618ar5eVqFDAjmKn/63i1mLC1AVcn6Gg49qFg4tZUUNENMxFdSL5dwNOFLwSE
; seHSgUwHtAMHDshIw7Q0S1cY4RrZMIgHdRq6qmGbA5wrdD7AAzY6hHBDV1CxAQ8xgeX+6QlVF/hMAY
; wJo+116dxzGWTKWB5FeqB+7xO0ZPjIg5p6TGpqQ4BmC1smcCbQ+fZ2NBDJs42KaQseA4bXyKYHR9Eg
; 0oXPBcCqTPe+ytonrTaqmleTHC0PNF1hhOtAKAvt1XRhywUuNnTkVHfu3JGNlpfXhQQPo2KFPU4YdO
; nBUja4TACsC4im16vTBllFCEQRZ8+ejQpaOoRkp29CWT5bJWyFwMWCDqmffI0Qz3b6wAd4DBj2LmQL
; 7LzBowufDYC+wPR1Xt37zGsnjK0xzpw5Eww0XWGE8ynoqoRNAjd//nxhCp2rmKLAw93TmMrNZ8Xasc
; FjoOBxqccsGkymAPqE0LeZ3INOm5AzokJWDVo6hOQzLG7NA81VHCmDDdYkcKGhS4LHzbJil+3Ssty7
; yfSBT/CS8DFoEG3wvEjXaYXTF4CxgHS5Jt37po0ADcEr/QLOojb3AZqJMIJRj8lu0JzflziiA1sbcD
; 6hK/J2xPOs1KZRTVXMmOAxiBg47I+Jclo0xRASwphmck9Z7cF7salhrRo0HWGE9wwQZnIM1xBSF7Y5
; wIWEjkagM/ipK6jEAK8MPgYS5UN4vLzE3xTAqkG0udaie6delVpIW8hCg1YUQjIm09CFgi0TuDLwTK
; Gj0fBo5EW6uV0dwUPUoR6TCdWiwecCYJ1M5x7Z2o7SLFVA3CTQkmOR+2D1AdU6vmDL4yoXOB/ejoag
; sJR5Lm7eZfrABroi8Gzgo2yIHAWxp2iKoUkg2twD9079I7AhLvmCrAg0X7Dl5Wo8SFFVuXbfXq0NuH
; nz5okQ0BG6UAnOTeoKKq7g2Xi8MvCyAESIYPWxjupZJZQ+riXrHhmcCCS6gLmAVtTXLl4tL4TkAUKl
; SgjYYO3/AflRCgpGBzSoAAAAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R4
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MINI" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S85 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S85 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S240 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S240 ; wait for extruder temp

; intro line
M73 P1 R4
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P3 R4
G1 E-3.2 F2700
M73 P5 R4
G1 Z.2 F9000
;AFTER_LAYER_CHANGE
;0.2
G1 Z.4
G1 X73.12 Y75.202
G1 Z.2
G1 E3.2 F1500
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X92.325 Y56.529 E.83987
G1 X93.535 Y55.898 E.04279
M73 P6 R4
G1 X94.892 Y56.037 E.04277
G1 X95.686 Y56.576 E.03009
G1 X123.571 Y85.254 E1.25417
G1 X124.201 Y86.465 E.0428
G1 X124.062 Y87.822 E.04277
G1 X123.523 Y88.616 E.03009
G1 X87.675 Y123.471 E1.5677
G1 X86.465 Y124.102 E.04279
M73 P7 R4
G1 X85.108 Y123.963 E.04277
G1 X84.314 Y123.424 E.03009
G1 X56.429 Y94.746 E1.25417
G1 X55.799 Y93.535 E.0428
M73 P8 R4
G1 X55.938 Y92.178 E.04277
G1 X56.477 Y91.384 E.03009
G1 X73.076 Y75.244 E.72592
M204 P1250
; printing object test_sheet_50x40x025 id:0 copy 0
G1 E-2.24 F2700
;WIPE_START
G1 F7200
G1 X75.008 Y73.366 E-.96
;WIPE_END
G1 Z.4 F9000
G1 X59.247 Y93.104
G1 Z.2
M73 P9 R4
G1 E3.2 F1500
M204 P800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X93.966 Y59.346 E1.51834
G1 X120.753 Y86.896 E1.20481
G1 X86.034 Y120.654 E1.51834
M73 P10 R4
G1 X59.289 Y93.147 E1.20293
M204 P1250
M73 P11 R4
G1 X58.713 Y93.097 F9000
M204 P800
;TYPE:External perimeter
M73 P12 R4
G1 F1200
G1 X93.974 Y58.813 E1.54202
G1 X121.287 Y86.903 E1.22845
G1 X86.026 Y121.187 E1.54202
M73 P13 R4
G1 X58.755 Y93.14 E1.22656
M204 P1250
M73 P14 R4
G1 X59.055 Y92.888 F9000
M73 P15 R4
G1 E-2.24 F2700
;WIPE_START
G1 F7200
G1 X60.685 Y91.259 E-.96
;WIPE_END
G1 Z.4 F9000
G1 X120.585 Y86.902
G1 Z.2
G1 E3.2 F1500
M204 P800
;TYPE:Solid infill
;WIDTH:0.420977
G1 F1200
G1 X93.691 Y60.008 E1.19562
G1 X93.42 Y60.272 E.01189
M73 P16 R4
G1 X120.194 Y87.045 E1.19026
G1 X119.923 Y87.309 E.01189
G1 X93.149 Y60.535 E1.19028
G1 X92.878 Y60.799 E.01189
M73 P17 R4
G1 X119.652 Y87.573 E1.19028
G1 X119.381 Y87.836 E.01187
G1 X92.607 Y61.062 E1.19028
G1 X92.336 Y61.326 E.01189
M73 P18 R3
G1 X119.11 Y88.1 E1.19028
G1 X118.839 Y88.363 E.01187
M73 P19 R3
G1 X92.065 Y61.589 E1.19028
G1 X91.794 Y61.853 E.01189
G1 X118.567 Y88.627 E1.19026
G1 X118.296 Y88.89 E.01187
M73 P20 R3
G1 X91.522 Y62.117 E1.19026
G1 X91.251 Y62.38 E.01187
M73 P21 R3
G1 X118.025 Y89.154 E1.19028
G1 X117.754 Y89.418 E.01189
G1 X90.98 Y62.644 E1.19028
G1 X90.709 Y62.907 E.01187
M73 P22 R3
G1 X117.483 Y89.681 E1.19028
G1 X117.212 Y89.945 E.01189
M73 P23 R3
G1 X90.438 Y63.171 E1.19028
G1 X90.167 Y63.434 E.01187
G1 X116.941 Y90.208 E1.19028
G1 X116.67 Y90.472 E.01189
M73 P24 R3
G1 X89.896 Y63.698 E1.19028
G1 X89.625 Y63.962 E.01189
M73 P25 R3
G1 X116.399 Y90.735 E1.19026
G1 X116.128 Y90.999 E.01189
G1 X89.354 Y64.225 E1.19028
G1 X89.083 Y64.489 E.01189
M73 P26 R3
G1 X115.857 Y91.263 E1.19028
G1 X115.586 Y91.526 E.01187
M73 P27 R3
G1 X88.812 Y64.752 E1.19028
G1 X88.541 Y65.016 E.01189
G1 X115.314 Y91.79 E1.19026
G1 X115.043 Y92.053 E.01187
M73 P28 R3
G1 X88.27 Y65.279 E1.19026
G1 X87.998 Y65.543 E.01192
M73 P29 R3
G1 X114.772 Y92.317 E1.19028
G1 X114.501 Y92.58 E.01187
G1 X87.727 Y65.807 E1.19026
G1 X87.456 Y66.07 E.01187
M73 P30 R3
G1 X114.23 Y92.844 E1.19028
G1 X113.959 Y93.108 E.01189
M73 P31 R3
G1 X87.185 Y66.334 E1.19028
G1 X86.914 Y66.597 E.01187
G1 X113.688 Y93.371 E1.19028
G1 X113.417 Y93.635 E.01189
M73 P32 R3
G1 X86.643 Y66.861 E1.19028
G1 X86.372 Y67.124 E.01187
M73 P33 R3
G1 X113.146 Y93.898 E1.19028
G1 X112.875 Y94.162 E.01189
G1 X86.101 Y67.388 E1.19028
G1 X85.83 Y67.652 E.01189
M73 P34 R3
G1 X112.604 Y94.425 E1.19026
G1 X112.333 Y94.689 E.01189
G1 X85.559 Y67.915 E1.19028
G1 X85.288 Y68.179 E.01189
M73 P35 R3
G1 X112.061 Y94.953 E1.19026
G1 X111.79 Y95.216 E.01187
M73 P36 R3
G1 X85.017 Y68.442 E1.19026
G1 X84.745 Y68.706 E.01192
G1 X111.519 Y95.48 E1.19028
G1 X111.248 Y95.743 E.01187
M73 P37 R3
G1 X84.474 Y68.969 E1.19028
G1 X84.203 Y69.233 E.01189
M73 P38 R3
G1 X110.977 Y96.007 E1.19028
G1 X110.706 Y96.27 E.01187
G1 X83.932 Y69.497 E1.19026
G1 X83.661 Y69.76 E.01187
M73 P39 R2
G1 X110.435 Y96.534 E1.19028
G1 X110.164 Y96.798 E.01189
M73 P40 R2
G1 X83.39 Y70.024 E1.19028
G1 X83.119 Y70.287 E.01187
G1 X109.893 Y97.061 E1.19028
G1 X109.622 Y97.325 E.01189
M73 P41 R2
G1 X82.848 Y70.551 E1.19028
G1 X82.577 Y70.814 E.01187
M73 P42 R2
G1 X109.351 Y97.588 E1.19028
G1 X109.08 Y97.852 E.01189
G1 X82.306 Y71.078 E1.19028
G1 X82.035 Y71.342 E.01189
M73 P43 R2
G1 X108.809 Y98.115 E1.19026
G1 X108.537 Y98.379 E.01192
M73 P44 R2
G1 X81.764 Y71.605 E1.19026
G1 X81.492 Y71.869 E.01192
G1 X108.266 Y98.643 E1.19028
G1 X107.995 Y98.906 E.01187
M73 P45 R2
G1 X81.221 Y72.132 E1.19028
G1 X80.95 Y72.396 E.01189
M73 P46 R2
G1 X107.724 Y99.17 E1.19028
G1 X107.453 Y99.433 E.01187
G1 X80.679 Y72.659 E1.19028
G1 X80.408 Y72.923 E.01189
M73 P47 R2
G1 X107.182 Y99.697 E1.19028
G1 X106.911 Y99.96 E.01187
M73 P48 R2
G1 X80.137 Y73.187 E1.19026
G1 X79.866 Y73.45 E.01187
G1 X106.64 Y100.224 E1.19028
G1 X106.369 Y100.488 E.01189
M73 P49 R2
G1 X79.595 Y73.714 E1.19028
G1 X79.324 Y73.977 E.01187
G1 X106.098 Y100.751 E1.19028
M73 P50 R2
G1 X105.827 Y101.015 E.01189
G1 X79.053 Y74.241 E1.19028
G1 X78.782 Y74.504 E.01187
M73 P51 R2
G1 X105.556 Y101.278 E1.19028
G1 X105.284 Y101.542 E.01192
G1 X78.511 Y74.768 E1.19026
G1 X78.24 Y75.032 E.01189
M73 P52 R2
G1 X105.013 Y101.806 E1.19026
G1 X104.742 Y102.069 E.01187
M73 P53 R2
G1 X77.968 Y75.295 E1.19028
G1 X77.697 Y75.559 E.01189
G1 X104.471 Y102.333 E1.19028
G1 X104.2 Y102.596 E.01187
M73 P54 R2
G1 X77.426 Y75.822 E1.19028
G1 X77.155 Y76.086 E.01189
M73 P55 R2
G1 X103.929 Y102.86 E1.19028
G1 X103.658 Y103.123 E.01187
G1 X76.884 Y76.349 E1.19028
G1 X76.613 Y76.613 E.01189
M73 P56 R2
G1 X103.387 Y103.387 E1.19028
G1 X103.116 Y103.651 E.01189
M73 P57 R2
G1 X76.342 Y76.877 E1.19028
G1 X76.071 Y77.14 E.01187
G1 X102.845 Y103.914 E1.19028
G1 X102.574 Y104.178 E.01189
M73 P58 R2
G1 X75.8 Y77.404 E1.19028
G1 X75.529 Y77.667 E.01187
M73 P59 R2
G1 X102.303 Y104.441 E1.19028
G1 X102.032 Y104.705 E.01189
M73 P59 R1
G1 X75.258 Y77.931 E1.19028
G1 X74.987 Y78.195 E.01189
M73 P60 R1
G1 X101.76 Y104.968 E1.19024
G1 X101.489 Y105.232 E.01189
M73 P61 R1
G1 X74.715 Y78.458 E1.19028
G1 X74.444 Y78.722 E.01189
G1 X101.218 Y105.496 E1.19028
G1 X100.947 Y105.759 E.01187
M73 P62 R1
G1 X74.173 Y78.985 E1.19028
G1 X73.902 Y79.249 E.01189
M73 P63 R1
G1 X100.676 Y106.023 E1.19028
G1 X100.405 Y106.286 E.01187
G1 X73.631 Y79.512 E1.19028
G1 X73.36 Y79.776 E.01189
M73 P64 R1
G1 X100.134 Y106.55 E1.19028
G1 X99.863 Y106.813 E.01187
M73 P65 R1
G1 X73.089 Y80.04 E1.19026
G1 X72.818 Y80.303 E.01187
G1 X99.592 Y107.077 E1.19028
G1 X99.321 Y107.341 E.01189
M73 P66 R1
G1 X72.547 Y80.567 E1.19028
G1 X72.276 Y80.83 E.01187
G1 X99.05 Y107.604 E1.19028
G1 X98.779 Y107.868 E.01189
M73 P67 R1
G1 X72.005 Y81.094 E1.19028
G1 X71.734 Y81.357 E.01187
M73 P68 R1
G1 X98.507 Y108.131 E1.19026
G1 X98.236 Y108.395 E.01189
G1 X71.463 Y81.621 E1.19026
G1 X71.191 Y81.885 E.01192
M73 P69 R1
G1 X97.965 Y108.658 E1.19026
G1 X97.694 Y108.922 E.01189
M73 P70 R1
G1 X70.92 Y82.148 E1.19028
G1 X70.649 Y82.412 E.01189
G1 X97.423 Y109.186 E1.19028
G1 X97.152 Y109.449 E.01187
M73 P71 R1
G1 X70.378 Y82.675 E1.19028
G1 X70.107 Y82.939 E.01189
M73 P72 R1
G1 X96.881 Y109.713 E1.19028
G1 X96.61 Y109.976 E.01187
G1 X69.836 Y83.202 E1.19028
G1 X69.565 Y83.466 E.01189
M73 P73 R1
G1 X96.339 Y110.24 E1.19028
G1 X96.068 Y110.503 E.01187
M73 P74 R1
G1 X69.294 Y83.73 E1.19026
G1 X69.023 Y83.993 E.01187
G1 X95.797 Y110.767 E1.19028
G1 X95.526 Y111.031 E.01189
M73 P75 R1
G1 X68.752 Y84.257 E1.19028
G1 X68.481 Y84.52 E.01187
M73 P76 R1
G1 X95.255 Y111.294 E1.19028
G1 X94.983 Y111.558 E.01192
G1 X68.21 Y84.784 E1.19026
G1 X67.938 Y85.047 E.01189
M73 P77 R1
G1 X94.712 Y111.821 E1.19028
G1 X94.441 Y112.085 E.01189
M73 P78 R1
G1 X67.667 Y85.311 E1.19028
G1 X67.396 Y85.575 E.01189
G1 X94.17 Y112.348 E1.19026
G1 X93.899 Y112.612 E.01189
M73 P79 R1
G1 X67.125 Y85.838 E1.19028
G1 X66.854 Y86.102 E.01189
M73 P80 R0
G1 X93.628 Y112.876 E1.19028
G1 X93.357 Y113.139 E.01187
G1 X66.583 Y86.365 E1.19028
G1 X66.312 Y86.629 E.01189
M73 P81 R0
G1 X93.086 Y113.403 E1.19028
G1 X92.815 Y113.666 E.01187
M73 P82 R0
G1 X66.041 Y86.892 E1.19028
G1 X65.77 Y87.156 E.01189
G1 X92.544 Y113.93 E1.19028
G1 X92.273 Y114.193 E.01187
M73 P83 R0
G1 X65.499 Y87.42 E1.19026
G1 X65.228 Y87.683 E.01187
G1 X92.002 Y114.457 E1.19028
G1 X91.73 Y114.721 E.01192
M73 P84 R0
G1 X64.957 Y87.947 E1.19026
G1 X64.686 Y88.21 E.01187
M73 P85 R0
G1 X91.459 Y114.984 E1.19026
G1 X91.188 Y115.248 E.01189
G1 X64.414 Y88.474 E1.19028
G1 X64.143 Y88.737 E.01187
M73 P86 R0
G1 X90.917 Y115.511 E1.19028
G1 X90.646 Y115.775 E.01189
M73 P87 R0
G1 X63.872 Y89.001 E1.19028
G1 X63.601 Y89.265 E.01189
G1 X90.375 Y116.038 E1.19026
G1 X90.104 Y116.302 E.01189
M73 P88 R0
G1 X63.33 Y89.528 E1.19028
G1 X63.059 Y89.792 E.01189
M73 P89 R0
G1 X89.833 Y116.566 E1.19028
G1 X89.562 Y116.829 E.01187
G1 X62.788 Y90.055 E1.19028
G1 X62.517 Y90.319 E.01189
M73 P90 R0
G1 X89.291 Y117.093 E1.19028
G1 X89.02 Y117.356 E.01187
M73 P91 R0
G1 X62.246 Y90.582 E1.19028
G1 X61.975 Y90.846 E.01189
G1 X88.749 Y117.62 E1.19028
G1 X88.478 Y117.883 E.01187
M73 P92 R0
G1 X61.704 Y91.11 E1.19026
G1 X61.433 Y91.373 E.01187
M73 P93 R0
G1 X88.206 Y118.147 E1.19026
G1 X87.935 Y118.411 E.01189
G1 X61.161 Y91.637 E1.19028
G1 X60.89 Y91.9 E.01187
M73 P94 R0
G1 X87.664 Y118.674 E1.19028
G1 X87.393 Y118.938 E.01189
M73 P95 R0
G1 X60.619 Y92.164 E1.19028
G1 X60.348 Y92.427 E.01187
G1 X87.122 Y119.201 E1.19028
G1 X86.851 Y119.465 E.01189
M73 P96 R0
G1 X60.077 Y92.691 E1.19028
G1 X59.806 Y92.955 E.01189
M73 P97 R0
G1 X86.58 Y119.728 E1.19026
G1 X86.309 Y119.992 E.01189
G1 X59.415 Y93.098 E1.19562
M204 P1250
; stop printing object test_sheet_50x40x025 id:0 copy 0
G1 E-2.24 F2700
;WIPE_START
M73 P98 R0
G1 F7200;_WIPE
G1 X61.32 Y95.003 E-.96
;WIPE_END
G1 Z.4 F9000
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z2.2 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z30.2 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
; filament used [mm] = 187.76
; filament used [cm3] = 0.45
; filament used [g] = 0.57
; filament cost = 0.02
; total filament used [g] = 0.57
; total filament cost = 0.02
; estimated printing time (normal mode) = 4m 54s

; prusaslicer_config = begin
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 90
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 50
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"printer_model==\"MINI\" and nozzle_diameter[0]!=0.8 and nozzle_diameter[0]!=0.6"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1250
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; dynamic_overhang_speeds = 25,20,15,15
; elefant_foot_compensation = 0.2
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = 1
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 20
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.27
; filament_deretract_speed = 25
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 7
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = 1
; filament_retract_speed = 45
; filament_settings_id = "Prusament PETG @MINI"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 85
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 240
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = "0.20mm QUALITY @MINI";;
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 50
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 30
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhang_overlap_levels = 60%,40%,20%,0%
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MINI - Copy
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.6}0.12{elsif nozzle_diameter[0]==0.8}0.06{else}0.2{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 30%
; temperature = 250
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
