; generated by PrusaSlicer 2.5.0+win64 on 2023-02-21 at 19:11:15 UTC


;
; thumbnail begin 16x16 536
; iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABWUlEQVR4AaWTS07DQBBE51bs8rUd/+
; I4H1tI5CMkWHCCXACcc3GyJq+hLG9IFlm03NNTVePp6Qqj0cjG47FNJhObTqc2m81sPp9bFEVWlqVV
; VWVJkniNPTBg4cANQ1Icxw5O09SJeZ57vlwurSgK3wMzFAsAFouFB/lqtbK6rv30YSBCPcsyx0oooI
; o6J+52O9tsNr3Ier32IKdGsEaMw+AGFNlo27YX2G63njdN40FOjT3EJA43sNDGa1tbd8rt65R5kPfr
; Y2afx9Te2sqx/DEHByWInF8K+/54uhlgdE16E9QcfvG8L+8LXDFg4cB9XOCRK7iAOupNbCrr9pF1h9
; guh8Qux7+45qq9P/++AiLw/BlRUuHeM/LlyTVUQaPLMGlw/hskcgTpPnh4QR5gPFFUTzS+BLlENPri
; 9GbCfUMzQcJMBGSNLhiwvZlkZwkN7SyPkMuBIsrOPw6O94/ErLhsAAAAAElFTkSuQmCC
; thumbnail end
;

;
; thumbnail begin 220x124 8672
; iVBORw0KGgoAAAANSUhEUgAAANwAAAB8CAYAAAACRt5vAAAZL0lEQVR4Ae2dR7cVxRbH+xO96RsSDY
; BZUSSDoICBDBJFEDAskWwAMSBJQBmYRdd6U5041+/Sb/3qrbqrb98Otat2dde5rwZ7AYdzuiv9ev/3
; rtDFnDlzyiabO3duq82bN6/R5s+fb+yBBx4oH3nkkXLnzp3mzwULFjTawoULG43fN9mDDz7Yag899F
; CjPfzww522aNGiTlu8ePGUPf300+V7771XPvPMM+WSJUumPufvvkb7DGkhZa22xbJly8qXXnqpXLNm
; zbTP+9qzrz/a+rGr79vGS9v4ahuP/Gbfvn3l8uXLzd/teG4b712MtHFVaMNWta1bt5afffaZqUAs2H
; xAcwWsauvWrSt//fXXcteuXclDNRSMzz77bHnjxo3y+PHjre3mC58UvFDouOfly5fLAwcOTINNG7oi
; FmwYFXn00UfLJ554wjwR2yqfMmjYxo0by5UrV5ZPPfXUIHDRZho2BITch/YBPvp5EsFjbKJeqAv/bh
; vPGtAVLrD5gFY3Om/79u2mY1xg0wLNFzIGE3Lp4MGDpsxacGnBNCaUTW3x/PPPl6tXry5fe+21znb1
; hU8DvPq4oy5HjhwpH3vssUavpwXeDOC0vVqbfERaXr16tdy2bVvrk6gNtiFBw/bv31/+9ttv5dq1a7
; 0gSw2sWCBW24aBe/78+fLKlStTamBM8Lq8HWPxq6++Kjdv3jz1WdPY1fZ2xVCwWaMxeRoi0WhAX68m
; Bc0FMuzxxx83kCGT7ICKBRgDdAyLBaBtq02bNhmZ9txzz7UmXVzhk4Dn6u3oXxJf3NcloaIJXaEBmy
; QLaSuNZl6xYoWpfFtjDQkag+rll18ut2zZYiSkJmBjgRUTxL724cGFxAQ+rj02eIw5HvSENZTPfibJ
; YmpAV4wBmzU65eOPPy5PnDhhGs9HPkpBa4o/bDm+/vpr8yAIgSxkwFOOGBYbwq72Qprfu3fPKJq+qQ
; Zf8FxkJmEM4YxN+fclVGJBV2jDJslC2sYg5c5Af/LJJ4O9mgQ0DOlDJ+DZfCBLBaqhYPSBD0+3fv16
; 09Zt/SABTxrfMb5QU/zWNaEilZiu0BV9sIXEa5IMJCnlpUuXmoFPQ0u9mhQ07secGpK2LiE1INMGg/
; J22RggSuF74YUXTObXLhyIAV4VNBIiwE59fDOZGnFdI3BjwmYbiIZlEvWTTz4xHi9EPi7pmCcjmP/m
; m2/KDz/8UA2yGBDFshgAusIHBLS9jaUk4LnKTL7LiqCLFy+askszmTGhK1KBrWo8BYGCIFfq1bpAw4
; glVq1aZTxbH2hakI0FViwQQ+CjzfFwqAv6mO9rgGfHCfWgj+lfPvedPogFXREjZnOBrS9Wo3OQejwR
; ie185aMFjU7mqYqe7xoUGpCFDHrqqmmxAQyBD4kJdMRXXZPqLjKT77GUkDiR+0ozmdrQtXFVxIYtJN
; 1PQ+7Zs8dklwBF4tWqsQOp6d9//90sTPUBTRswbaiGgjEEvrZ2B5Bbt26VJ0+enCY9Jd6OSfbPP/+8
; PHr0qPle6PRBTOiKlGGzRjKFLBdSsNrwffKRDuQ3r7zyislESkDTgiwVuLQh9IWvqQ+43t69e02CA3
; i6oKuDB7BISMxn+mBo6IrUYOuK1WhU4jtiuz6vBmisFmELiRZoMQBjgA1pMQDUAs+CY+PrLvAoG+s2
; gZTvuGYyx4auGAs233Q/nXH9+vWpvXZ10Oi4w4cPGwm5YcOGYNA0IRsaLm0IQ+BzBY/Pzp07Z7bKVL
; 1dFTz69ebNmyZmq3s838nyoaArUoWtK1aj80mA4Olslgujw/mM1Q10ckzQYsLFlIiGxYQwJnj8mzCA
; hFkVOv6P/mWuljBDkslMBbpi0mCrykfkBxqe+O7FF1802S4kRizQNCHTgmoIGEPgCwUP6OhjQgT6mZ
; CiSWZOCnRF6rD1xWpA9ueff5Z//fWX6Zg+2KSgaUA2NlyaEPrCJwGvLjMvXbpU/vPPP2Y9ZF9slzp0
; vcDFgs0lXuuDjXk6pgtI9+/YscPAh9SIDVoMwJgnjGkxAIwNHt+nP+lbEmAcf8B3Q6FzSaZoQdcJnI
; t3SwE2OoJJUyQGE6f2SQiASA4+5ztdsGmDlgpYsUAcArwqbABGX2JVb4fEZIqHa6cIXZ+XK0Jgc1lB
; ogFb9YlG0Pztt9+adZBNGS468+233zZZLjomFLRQyLTA4EnfZUMC6AOfK3hc/4MPPjD9Z9VKvZ+B8e
; 7du2ZaoMvbxYCuiQEJdMUkwYYHQ17wlOuL1dhMyvfoNNuxEthCQNOGScu04ZOC1wcd/UtyhFitqlCa
; Yjvqc/r0aVPOrhUqqUFXaMVtMRIkthHpQOIz0sFNmay2eI1OJr3M3J0FLxZoqcGlDWFM8PgeYQBL8C
; iTJKFiQ4jq9MEQiRTfeK7QiNt8VpC4wsZKEQ7zYXV53yR2W6zGsqFr166Za/nIxxDIQmDgie9jsQGU
; gtclM3mQslaWMIDPXBIq9XHAPTgQiK1dWtA1jWmNeK4YI0niAhsNSefSiHSKL2zWmJ9jBQpJlvog0A
; ZtCKiGgDE2ePQFqgXpL0moNEHH744dOzZ1+FMM6DSSKEVsKekDGwODSW0khss6SJfEiO1kYjvgI6Gi
; CVqKcGlCqAke90QGEqtZEF0SKn3QYbaP7fRBbOik0rLQlJKhsNFgzLXcv39/RjrYdSLbJSlCZ7MlBK
; nJgIkJmi8EPP1DLBZ8oeARU9++fduECC5JFZ+JckBjxzcHQ3HdsaFrBC4F2Fgp8u67785YB6kJm5WQ
; 3IvTwvizbbD4gjYkWDFB1ASPz7nmoUOHzMNUksn0gQ5jgTsyMwVPNw24MaWkPWME7c0cW9sZIxqwNc
; kbmx1DZlYHSyzQhgZMA0Af8Kqw0bYYUs8lttOQl9XpJKaS6hJzLGlZjOndaNwLFy4YeUejDg2bHRCA
; /sUXXxjvaj2eK2gxIaMsPjYGfG3gkahCQrKlpiu2iw0dUpbJ8upeyjG8XBHq3Xxho0FeffXVKZevBZ
; trur9J8rBFn4wZAysUtCHAigliKHhcg8QXWWYGuUtCxUVihkDHckB7kpcGdD5erhjSu1nQaFz2s9FA
; Q8PWF6sxUND+ZDH5uxS2lADTANAHOuQj26UY4H2x3dDQ2aP6KH8TdLG9XDGklKQD79y5Y6RbvRFSgK
; 3q1Sgjb4Gxq1S6QBsCMrxEl40Jn20fynH27Fkjz9ukeQrQARll5Wh74sohpWU04JpkJPICLV1fI1kH
; LkbMVu/kgysWlf/Z/O9sIxhtL4UuNKarjzfGIA8J3tALfF3QRQEulnejsjQo8VrTgmSpd9OADTu0Mg
; M3ltH2Pp6uDzqptLTjES9d93SxvJwKcE2wUREyUz///LNZw9i2A0BbSrrKyAzcuMD5ykttaVkdkxxe
; 9OabbzpBFxU4H+9GY7CniXWQbbCFSsmQmC0DNz5wY0DX5uUwfssial4zHerlOoHT9G5UgpUE7Guqry
; jRlJK+qf8MXFrANUHnM0+nIS1txpI/kZj8qe3lCi3vRuFYm/jDDz+YBujacjOGd6tnyzJw6QDnAt1Q
; Xq46TcBxi8hMfq/l5QqtZAleDQlJ4ZrWS0q8W2zY/gfc4okapLMLuMVOUwaa0Em9HMbnzMlyapiVmK
; HJExFw9ZtZqDhbograkN7NBzbSwRm4cYFrWw4mgW4IL2dBYzqLe4SuPil85SQV4LAXS3/XboCUvJud
; pM3AjQ9cE3SpebkqdCxV4y09lNtXVhY+cpKbkz5lz5HL9htf7xYLtgxcOsDFhs7Xy7VNhLO7hMnyKn
; QSWVlI5KQFCwnZt2bSZ95N07v1rfg/vCoDN5bR9n07Dcbwcn2ysmosdWOtqFRWFq5ykorzxpLdu3d3
; LuPS8m514DS9WwYuLeC0vZxWLNe3xpLvnDlzxuzldJWVhYt3o2As5GV5lsuOAI1VJRLvJoUtA5cecF
; LoYs3LSbwcLFAuTgxD9bl4uU7g7AVZmiXZghNbToZ6N9bOZeDGBa5pe89QGUtN4Ko8MFnuBRw/YF7t
; 3r17MzIyQ8hJzditbT9bBi494PqgSyl50jY9wLIwTAQcy7LsdvS+tZNjA+fj3TJwaQAX6uVSBI7fkL
; 0ntmsFrurZWOFPRSU7AyZNTmbgZgdwKcnKeqaS/2PXO9euQmeA48scecBO3Xq2ZWjgYsrJ6i7lDFwa
; wEmh05KVsYGzxmQ5OxD4rQEO8lh0zAw6N+tbzjUb5GQGbnKBmwRZWU2c8BnH9HGcA98vSGfyoev6yT
; GB05KTGbjZA5xEVo4BnDV+R06k8N0dIAFujPhtac9JWxm4dIDrg27sOM4XuKbpgUKyYHnohEms+A17
; Y/WSiRqks8loewlwIXHcmImTphUnEwtciJzMwE02cJI4LjngJJIypQxlBi4DNwmZyhmScmjgUshQZu
; AycH2JkwxcBi4Dl4HLwGXLwGXgMnAZuAxcBi5bBi4Dly0DN5uBy9MC2f6vpwXyxHe22QxcXmnyaF7a
; lYHLS7smfvGyFLjDqzJwYxltHwu4lBcvG+A4+GTM7Tmxdgvk7TkpAzfO9pwu4OrjVQO4evy2adOmsu
; ACnJu+bdu2UYDLG1AzcKllKLWBAzTeGT+VNOHmp0+fLk+dOjXjR13AdcVxGbhssxG4rvitCbgjR46Y
; o9EX2yMWbAzHFyggJ3ZR8ElMnNShq3dkFboMXBrANfWRr5xMKWHCv1GOfGdG0qSaOOGiVPTAgQPmy2
; MDFyuOy8ClCdwY8Zs2cG+99Va5efPmGQmT1nMpuTCHWV6/ft0UdDbGcRm4yQcutfiNzziM6/jx440Z
; yt6jzu0A5qgvH+BSkJVt0GXgxgdO07sNISe7gKN869atM9doylA6v8yDC1Ng3gdHpVKQlRpeLgM32c
; BJvFtMOcl3OGWZ63ZNCYjensOFt2zZYs7Wg+LUZKUPdBm4cYGL6d2GkpM8NL777rtpL/FwBs4FOipC
; 5ZlXGFpWaidPMnCzB7ghvFsdOF7GyEsZ+V7fhHfQK4etxOQA2dWrV6vKyiG9XH7l8HiWyiuHfeQkkJ
; 08eXJaDOfq3bzf8Y2tWLHCvIju0KFD0WSldixXhS4DlwZwTX0UK3YLlZO8kBQJyQnKki05rcC5yMqq
; UWhuzltCKPAkebkMXJrApejdMHIYeDf+Llk/WedLBFzbJDgNwQqVrVu3ju7lXKHLwI0PXEzYtLwbb/
; 9lnTG/l27HaQRu4cKF3sDVobtw4UJ57tw5U6GYXk6aQGmC7tDKRRM1SGcXcIt6YZMmSmJ4t/fff7/8
; 8ssvW2GTAgdrM4Dz9XIYhSV7g/EEk3g5zXk5F+gycOkAJ4VNMzPZ5N24HtNf5Cl8N5s2eTcV4Jrm5G
; gQ5ih27do1o0K+Xk5bWmbg0gUuppTs82779+832Xd+J9mKIwJOCp3Llh0qxtYE1mMCn4+Xk0pLCXQZ
; uDSAC4UtREpWgeM6165dM+/ndlmoLE2WWM68gJNsTGUd5tq1a81TY4gEiit0GbjxgZPCFitRgnRknO
; IYXBcq+3i3acBpxnJ16Kjs8uXLjcSkIYeWlk3QbVv6QHl12b+yjWA7nn2wF7YhpCSfvfHGG1MrRnz2
; vUlgUwXOZVEzq1Pu3LljUq0h0lILuq7J8cOHD5uyMv9S3y1eNzqsy5YtWyY25jdDzOeeffXoagPaaM
; 2aNWYxBNk9vu8yqT0GbBiK66effjIpfwlsqsDF9HIWOjqHnbDIzBSho3ysFaUjGLh9p39JwPOFL6a5
; lLkPtLpt377dZPlQNSnCZkMcq7a61kxqejd14Fyho9JoZqYP6BTfeE4bOiBbv369GSxti561wBsTPt
; fySUGrTmbTv3i8HTt2mO/Hgk0St1F3ykPM5rJAWdu7GeAWLFhQjgEdRqfcuHHD6GhfL6eRSGFAnD17
; 1hz2Qmf07TTQBi8mhD5l8AGtaeUI1+JwKtuu2gkSiXfbs2dP+eOPP5oVUWPBBmtOwMWQltV0LJ6Fzu
; HvQ0KHMRDwtMggBk1bXBcCni98Q1pf+SWg1SUk+8VQDZiLV9OEjc9RUZwx4rJAWUtKdgI3ppezRqMg
; 57AhoGNAsPqb+3Fv14RKKHipAOhazhDQqsY9kZist8XzDgEbD1IbS0r2usXybp3AjQEdHfDRRx+Z9Z
; g0tAZ0TeDZrUUczskAkWYxXcCTwBcbQmk5+urV1SZ9sRrZXxZDsMNEOqktge3ixYtmIpvrjg1bI3Ax
; pKUPdDQgT0F7PqY2dMSNSBwyka4JlVDwfOAb2lzqIAWtLTFChpApIjye9XJasNlMM33ssu1GG7Yu7z
; YDuCGkpQt0NBQdARQbN27shc5lyoABw/WYA2QgdMV1vuC5wpcCgK7l7KuvBLS6hMTLYTwEpan/JtiY
; bgJmyu0DW0wp6QzcENKyDToa8ejRo0aCoMN9oSNg5gCknTt3NsYMMcCTwBcTRJ8yuNQtBLSqhOQBeO
; vWLbMKyX4mhY0y37x502REXTeUDi0lW4FLRVpWl39t2LDBPL3qErMPOjqPAH337t0znqJa4MWEb0gL
; gUwKWl1C8mDYu3ev6SN+I4GN39oMaBtsKUjJKeDmz59f+kBXL0BMT2e9HbocT9cHHh3F91hRgGRpi+
; u0wXOFLwUAXcvZV98Q0OoSkqwisTuxHZ91gca/8Y78pjrfNoRn85GSGKwZ4Jqg85GWsaHDSOXfvXvX
; xGNN0NFx+/btMzKFlL9LQiUGeBL4YsHoe3+XummCVjWyqhwXfuLECfO7Jtjo119++cWECC47t4eGrQ
; k4y9kUcFrQ1QscAzrWOHJamH0K2o6w8oTUM4NCksXsgq4LPFf4QgCMba7l72qDrrZzhc1KSP4kDLDz
; o1XY7PIswIwNm1bcVmWsE7iUocOQFMAHZOh/dDySxCWhEgM8CXxjQSgtX199NUGrG/1K/E6/2l0QZK
; 0f6TgiITXYOoHzjee0oJMmUzD0/h9//FHev3/fDABJFrMPvFD4fAAMBTL0fi518oGsDbS+xAj/T3jw
; 999/m8RZF2haqX/NJEmdrxnATRJ0dAxPP95ld+zYMSM36CDp9EEoeK7waQCoba7l7qu/NmgWNhsiMF
; FO0ox7TSpsBrh58+aVkwBdFTwanI7giUeH2iceS7bITPKk95ks1wBPAt+QIPqUyaWuMUCzsRoxHCFC
; NVNNsox+5voSCZkCbLBmgHOFziWe84XONa4j+8Z2D156Z590VZlBh166dMlst3GZt/MFzxU+XwDHMN
; f69LWLBLQm2M6fP2/WQVYfplWvRkLl6tWr5uHqE69pwtaXJKnC1gtcatDR6KxIYOVIV1xHJ7L/yc7B
; uXi7LvBc4JMAmAKEkrK61L2r7VxB414kSei7vsQIXu711183v6t6uRRhawQuRFq6QucyT9cEnV1biY
; SUJFQYCOj+emo5BLwY8MUAMvT+oZBJQMNsBpKySxIjZKoJISiPD2wu82y+Gck6bDOAGwu6rriOSU52
; hePVXKYOmsBjRznbcehUCXha8GlBGMskdfCFrA00HoasleXgoT7Q2uI1poSQoOwy4Tu+8Vps2BqBSw
; U669lYcQAo0jm7+rIw5CUH0zZJTBfwtOEbA0Tf8oVA1gaaXaiAfKzPrbmCVh0TXItMNffj+ynCZoCb
; O3dumRp0dtIT7ybJYrrITLJcdqC0DQQN+EIAHNtc6uYLmV33SPLLZ16tLwtpD3WljKnBBmsGuFDotM
; CjgVgfhzwAuNDpgzbwkKe3b9+eeq9d05EO2vClCqGk7KGQ2YUKnAfJvJqPfHRJ91OWy5cvm1CC68QC
; TQpbL3BDQkdD8dTjda50kGtCxRc8ZCpxAzFE2zF9UvB8AIwNZEhZXOvrAppNYr3zzjtmjk0DtK7ECP
; /Hggj7WuwxYWsETgqdpsSkkeyJTr7TB1KZac0eIsTAqaeiuwbSUAAOaRqA1SGzoCH1iNW6+kIqH10S
; I1yX+3IdvhNLQrrANgO4oaGj4ZjA5sCXqst3hU4LPNLKbAk5ePDgjMHiAp4EvrFh9C2nSxs0tR0r+7
; ///nujKGKB5hKrcXIAh1ORPBoLtkbgpDGdBLoqeDQCaVx2+lafPF3QacjMNvjwrshZe0xfl7kMvhAI
; xzbX+vW1E1toTp06Zb7rCpmPfHRNjJCk4fxR+/9toGnA1sZVK3Aa0LWtv6SyZAtpsK64bizw6Bi8Qd
; +AksCXKoTS8ru0CW3HhDQxeQqg1SUkSTM7hkLiNSlsBrg5c+aUUuh8kyl0MOdO4tWa3LoUPInMlMDH
; wDpz5ox5OlPmpukFLQBjQqlRFpc6V4HiIJ9PP/102uc+kIXIx77EiIWONblI3RjJkSaDNQOcJnRt4F
; F54jVS8X2xnWTeLhZ4DDZeP4v2b8qouQxETQiHMEmdmmIxjqxnK82QoEnS/XUJieQla0pZfdZFSmGb
; Blws6KgIjUimSJJQ0ZKZofDZwB+Z1JVhkwzWMWH0LWdX3fGmxEYxIAuVjy6JEaYOqCPXjAnbDOC0oS
; Pdbt22JKGSIngMKOrChHzX4NOAcGxzrR/pftaosmRu0kCrezSyl1euXDGxJ/8XA7ZG4LTAwyOwJ42U
; u2SiPAXwmuBjgNEZpJarT3LXwZkiiD5lr7YJL6CnTaSQpQRa1aiffd9E1ctpgGbtvzKomvjINPrXAA
; AAAElFTkSuQmCC
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; support material extrusion width = 0.35mm
; first layer extrusion width = 0.42mm

M73 P0 R4
M201 X2500 Y2500 Z400 E5000 ; sets maximum accelerations, mm/sec^2
M203 X180 Y180 Z12 E80 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T2500 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MINI" ; printer model check
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S170 ; set extruder temp for bed leveling
M140 S85 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S85 ; wait for bed temp
M204 T1250 ; set travel acceleration
G28 ; home all without mesh bed level
G29 ; mesh bed leveling 
M204 T2500 ; restore travel acceleration
M104 S240 ; set extruder temp
G92 E0
G1 Y-2 X179 F2400
G1 Z3 F720
M109 S240 ; wait for extruder temp

; intro line
M73 P1 R4
G1 X170 F1000
G1 Z0.2 F720
G1 X110 E8 F900
G1 X40 E10 F700
G92 E0

M221 S95 ; set flow
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.2 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P3 R4
G1 E-3.2 F2700
M73 P5 R4
G1 Z.2 F9000
;AFTER_LAYER_CHANGE
;0.2
G1 Z.4
G1 X74.177 Y74.177
G1 Z.2
G1 E3.2 F1500
M204 P800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X91.855 Y56.499 E.78386
G1 X93.056 Y55.852 E.04278
M73 P6 R4
G1 X94.415 Y55.972 E.04278
G1 X95.216 Y56.499 E.03008
G1 X123.501 Y84.784 E1.25417
G1 X124.148 Y85.985 E.04278
G1 X124.028 Y87.344 E.04278
G1 X123.501 Y88.145 E.03008
G1 X88.145 Y123.501 E1.56771
G1 X86.944 Y124.148 E.04278
M73 P7 R4
G1 X85.585 Y124.028 E.04278
G1 X84.784 Y123.501 E.03008
G1 X56.499 Y95.216 E1.25417
G1 X55.852 Y94.015 E.04278
M73 P8 R4
G1 X55.972 Y92.656 E.04278
G1 X56.499 Y91.855 E.03008
G1 X74.135 Y74.219 E.78198
M204 P1250
; printing object test_sheet_50x40x025 id:0 copy 0
G1 E-2.24 F2700
;WIPE_START
G1 F7200
G1 X75.945 Y72.409 E-.912
;WIPE_END
G1 E-.048 F2700
G1 Z.4 F9000
G1 X59.293 Y93.536
G1 Z.2
M73 P9 R4
G1 E3.2 F1500
M204 P800
;TYPE:Perimeter
;WIDTH:0.419999
G1 F1200
G1 X93.536 Y59.293 E1.51836
G1 X120.707 Y86.464 E1.20481
G1 X86.464 Y120.707 E1.51836
M73 P10 R4
G1 X59.336 Y93.578 E1.20293
M204 P1250
M73 P11 R4
G1 X58.76 Y93.536 F9000
M204 P800
;TYPE:External perimeter
M73 P12 R4
G1 F1200
G1 X93.536 Y58.76 E1.542
G1 X121.24 Y86.464 E1.22846
G1 X86.464 Y121.24 E1.542
M73 P13 R4
G1 X58.802 Y93.578 E1.22658
M204 P1250
M73 P14 R4
G1 X59.099 Y93.323 F9000
M73 P15 R4
G1 E-2.24 F2700
;WIPE_START
G1 F7200
G1 X60.61 Y91.766 E-.912
;WIPE_END
G1 E-.048 F2700
G1 Z.4 F9000
G1 X93.415 Y59.574
G1 Z.2
G1 E3.2 F1500
M204 P800
;TYPE:Solid infill
;WIDTH:0.422741
G1 F1200
G1 X120.306 Y86.465 E1.20107
G1 X120.037 Y86.734 E.012
M73 P16 R4
G1 X93.266 Y59.963 E1.19571
G1 X92.997 Y60.231 E.012
G1 X119.769 Y87.003 E1.19571
G1 X119.5 Y87.271 E.012
M73 P17 R4
G1 X92.729 Y60.5 E1.19571
G1 X92.46 Y60.769 E.012
G1 X119.231 Y87.54 E1.19571
G1 X118.963 Y87.808 E.012
M73 P18 R3
G1 X92.192 Y61.037 E1.19571
G1 X91.923 Y61.306 E.012
M73 P19 R3
G1 X118.694 Y88.077 E1.19571
G1 X118.426 Y88.345 E.012
G1 X91.655 Y61.574 E1.19571
G1 X91.386 Y61.843 E.012
M73 P20 R3
G1 X118.157 Y88.614 E1.19571
G1 X117.889 Y88.883 E.012
M73 P21 R3
G1 X91.117 Y62.111 E1.19571
G1 X90.849 Y62.38 E.012
G1 X117.62 Y89.151 E1.19571
G1 X117.351 Y89.42 E.012
M73 P22 R3
G1 X90.58 Y62.649 E1.19571
G1 X90.312 Y62.917 E.012
M73 P23 R3
G1 X117.083 Y89.688 E1.19571
G1 X116.814 Y89.957 E.012
G1 X90.043 Y63.186 E1.19571
G1 X89.774 Y63.454 E.012
M73 P24 R3
G1 X116.546 Y90.226 E1.19571
G1 X116.277 Y90.494 E.012
M73 P25 R3
G1 X89.506 Y63.723 E1.19571
G1 X89.237 Y63.991 E.012
G1 X116.009 Y90.763 E1.19571
G1 X115.74 Y91.031 E.012
M73 P26 R3
G1 X88.969 Y64.26 E1.19571
G1 X88.7 Y64.529 E.012
M73 P27 R3
G1 X115.471 Y91.3 E1.19571
G1 X115.203 Y91.568 E.012
G1 X88.432 Y64.797 E1.19571
G1 X88.163 Y65.066 E.012
M73 P28 R3
G1 X114.934 Y91.837 E1.19571
G1 X114.666 Y92.106 E.012
M73 P29 R3
G1 X87.894 Y65.334 E1.19571
G1 X87.626 Y65.603 E.012
G1 X114.397 Y92.374 E1.19571
G1 X114.129 Y92.643 E.012
M73 P30 R3
G1 X87.357 Y65.871 E1.19571
G1 X87.089 Y66.14 E.012
M73 P31 R3
G1 X113.86 Y92.911 E1.19571
G1 X113.591 Y93.18 E.012
G1 X86.82 Y66.409 E1.19571
G1 X86.552 Y66.677 E.012
M73 P32 R3
G1 X113.323 Y93.448 E1.19571
G1 X113.054 Y93.717 E.012
M73 P33 R3
G1 X86.283 Y66.946 E1.19571
G1 X86.014 Y67.214 E.012
G1 X112.786 Y93.986 E1.19571
G1 X112.517 Y94.254 E.012
M73 P34 R3
G1 X85.746 Y67.483 E1.19571
G1 X85.477 Y67.751 E.012
G1 X112.249 Y94.523 E1.19571
M73 P35 R3
G1 X111.98 Y94.791 E.012
G1 X85.209 Y68.02 E1.19571
G1 X84.94 Y68.289 E.012
M73 P36 R3
G1 X111.711 Y95.06 E1.19571
G1 X111.443 Y95.328 E.012
G1 X84.672 Y68.557 E1.19571
G1 X84.403 Y68.826 E.012
M73 P37 R3
G1 X111.174 Y95.597 E1.19571
G1 X110.906 Y95.866 E.012
M73 P38 R3
G1 X84.134 Y69.094 E1.19571
G1 X83.866 Y69.363 E.012
M73 P38 R2
G1 X110.637 Y96.134 E1.19571
G1 X110.369 Y96.403 E.012
M73 P39 R2
G1 X83.597 Y69.631 E1.19571
G1 X83.329 Y69.9 E.012
M73 P40 R2
G1 X110.1 Y96.671 E1.19571
G1 X109.831 Y96.94 E.012
G1 X83.06 Y70.169 E1.19571
G1 X82.792 Y70.437 E.012
M73 P41 R2
G1 X109.563 Y97.208 E1.19571
G1 X109.294 Y97.477 E.012
M73 P42 R2
G1 X82.523 Y70.706 E1.19571
G1 X82.254 Y70.974 E.012
G1 X109.026 Y97.746 E1.19571
G1 X108.757 Y98.014 E.012
M73 P43 R2
G1 X81.986 Y71.243 E1.19571
G1 X81.717 Y71.511 E.012
M73 P44 R2
G1 X108.489 Y98.283 E1.19571
G1 X108.22 Y98.551 E.012
G1 X81.449 Y71.78 E1.19571
G1 X81.18 Y72.049 E.012
M73 P45 R2
G1 X107.951 Y98.82 E1.19571
G1 X107.683 Y99.088 E.012
M73 P46 R2
G1 X80.912 Y72.317 E1.19571
G1 X80.643 Y72.586 E.012
G1 X107.414 Y99.357 E1.19571
G1 X107.146 Y99.626 E.012
M73 P47 R2
G1 X80.374 Y72.854 E1.19571
G1 X80.106 Y73.123 E.012
M73 P48 R2
G1 X106.877 Y99.894 E1.19571
G1 X106.608 Y100.163 E.012
G1 X79.837 Y73.392 E1.19571
G1 X79.569 Y73.66 E.012
M73 P49 R2
G1 X106.34 Y100.431 E1.19571
G1 X106.071 Y100.7 E.012
M73 P50 R2
G1 X79.3 Y73.929 E1.19571
G1 X79.032 Y74.197 E.012
G1 X105.803 Y100.968 E1.19571
G1 X105.534 Y101.237 E.012
M73 P51 R2
G1 X78.763 Y74.466 E1.19571
G1 X78.494 Y74.734 E.012
M73 P52 R2
G1 X105.266 Y101.506 E1.19571
G1 X104.997 Y101.774 E.012
G1 X78.226 Y75.003 E1.19571
G1 X77.957 Y75.272 E.012
M73 P53 R2
G1 X104.728 Y102.043 E1.19571
G1 X104.46 Y102.311 E.012
G1 X77.689 Y75.54 E1.19571
G1 X77.42 Y75.809 E.012
M73 P54 R2
G1 X104.191 Y102.58 E1.19571
G1 X103.923 Y102.848 E.012
M73 P55 R2
G1 X77.152 Y76.077 E1.19571
G1 X76.883 Y76.346 E.012
G1 X103.654 Y103.117 E1.19571
G1 X103.386 Y103.386 E.012
M73 P56 R2
G1 X76.614 Y76.614 E1.19571
G1 X76.346 Y76.883 E.012
M73 P57 R2
G1 X103.117 Y103.654 E1.19571
G1 X102.848 Y103.923 E.012
G1 X76.077 Y77.152 E1.19571
G1 X75.809 Y77.42 E.012
M73 P58 R2
G1 X102.58 Y104.191 E1.19571
G1 X102.311 Y104.46 E.012
M73 P59 R2
G1 X75.54 Y77.689 E1.19571
G1 X75.271 Y77.957 E.012
M73 P59 R1
G1 X102.043 Y104.729 E1.19571
G1 X101.774 Y104.997 E.012
M73 P60 R1
G1 X75.003 Y78.226 E1.19571
G1 X74.734 Y78.494 E.012
M73 P61 R1
G1 X101.506 Y105.266 E1.19571
G1 X101.237 Y105.534 E.012
G1 X74.466 Y78.763 E1.19571
G1 X74.197 Y79.032 E.012
M73 P62 R1
G1 X100.968 Y105.803 E1.19571
G1 X100.7 Y106.071 E.012
M73 P63 R1
G1 X73.929 Y79.3 E1.19571
G1 X73.66 Y79.569 E.012
G1 X100.431 Y106.34 E1.19571
G1 X100.163 Y106.609 E.012
M73 P64 R1
G1 X73.391 Y79.837 E1.19571
G1 X73.123 Y80.106 E.012
M73 P65 R1
G1 X99.894 Y106.877 E1.19571
G1 X99.626 Y107.146 E.012
G1 X72.854 Y80.374 E1.19571
G1 X72.586 Y80.643 E.012
M73 P66 R1
G1 X99.357 Y107.414 E1.19571
G1 X99.088 Y107.683 E.012
M73 P67 R1
G1 X72.317 Y80.912 E1.19571
G1 X72.049 Y81.18 E.012
G1 X98.82 Y107.951 E1.19571
G1 X98.551 Y108.22 E.012
M73 P68 R1
G1 X71.78 Y81.449 E1.19571
G1 X71.511 Y81.717 E.012
M73 P69 R1
G1 X98.283 Y108.489 E1.19571
G1 X98.014 Y108.757 E.012
G1 X71.243 Y81.986 E1.19571
G1 X70.974 Y82.254 E.012
M73 P70 R1
G1 X97.746 Y109.026 E1.19571
G1 X97.477 Y109.294 E.012
M73 P71 R1
G1 X70.706 Y82.523 E1.19571
G1 X70.437 Y82.792 E.012
G1 X97.208 Y109.563 E1.19571
G1 X96.94 Y109.831 E.012
M73 P72 R1
G1 X70.169 Y83.06 E1.19571
G1 X69.9 Y83.329 E.012
G1 X96.671 Y110.1 E1.19571
G1 X96.403 Y110.369 E.012
M73 P73 R1
G1 X69.631 Y83.597 E1.19571
G1 X69.363 Y83.866 E.012
M73 P74 R1
G1 X96.134 Y110.637 E1.19571
G1 X95.866 Y110.906 E.012
G1 X69.094 Y84.134 E1.19571
G1 X68.826 Y84.403 E.012
M73 P75 R1
G1 X95.597 Y111.174 E1.19571
G1 X95.328 Y111.443 E.012
M73 P76 R1
G1 X68.557 Y84.672 E1.19571
G1 X68.289 Y84.94 E.012
G1 X95.06 Y111.711 E1.19571
G1 X94.791 Y111.98 E.012
M73 P77 R1
G1 X68.02 Y85.209 E1.19571
G1 X67.751 Y85.477 E.012
M73 P78 R1
G1 X94.523 Y112.249 E1.19571
G1 X94.254 Y112.517 E.012
G1 X67.483 Y85.746 E1.19571
G1 X67.214 Y86.014 E.012
M73 P79 R1
G1 X93.986 Y112.786 E1.19571
G1 X93.717 Y113.054 E.012
M73 P80 R0
G1 X66.946 Y86.283 E1.19571
G1 X66.677 Y86.552 E.012
G1 X93.448 Y113.323 E1.19571
G1 X93.18 Y113.591 E.012
M73 P81 R0
G1 X66.409 Y86.82 E1.19571
G1 X66.14 Y87.089 E.012
M73 P82 R0
G1 X92.911 Y113.86 E1.19571
G1 X92.643 Y114.129 E.012
G1 X65.871 Y87.357 E1.19571
G1 X65.603 Y87.626 E.012
M73 P83 R0
G1 X92.374 Y114.397 E1.19571
G1 X92.105 Y114.666 E.012
M73 P84 R0
G1 X65.334 Y87.895 E1.19571
G1 X65.066 Y88.163 E.012
G1 X91.837 Y114.934 E1.19571
G1 X91.568 Y115.203 E.012
M73 P85 R0
G1 X64.797 Y88.432 E1.19571
G1 X64.529 Y88.7 E.012
M73 P86 R0
G1 X91.3 Y115.471 E1.19571
G1 X91.031 Y115.74 E.012
G1 X64.26 Y88.969 E1.19571
G1 X63.991 Y89.237 E.012
M73 P87 R0
G1 X90.763 Y116.009 E1.19571
G1 X90.494 Y116.277 E.012
M73 P88 R0
G1 X63.723 Y89.506 E1.19571
G1 X63.454 Y89.775 E.012
G1 X90.225 Y116.546 E1.19571
G1 X89.957 Y116.814 E.012
M73 P89 R0
G1 X63.186 Y90.043 E1.19571
G1 X62.917 Y90.312 E.012
M73 P90 R0
G1 X89.688 Y117.083 E1.19571
G1 X89.42 Y117.351 E.012
G1 X62.649 Y90.58 E1.19571
G1 X62.38 Y90.849 E.012
M73 P91 R0
G1 X89.151 Y117.62 E1.19571
G1 X88.883 Y117.889 E.012
G1 X62.111 Y91.117 E1.19571
G1 X61.843 Y91.386 E.012
M73 P92 R0
G1 X88.614 Y118.157 E1.19571
G1 X88.345 Y118.426 E.012
M73 P93 R0
G1 X61.574 Y91.655 E1.19571
G1 X61.306 Y91.923 E.012
G1 X88.077 Y118.694 E1.19571
G1 X87.808 Y118.963 E.012
M73 P94 R0
G1 X61.037 Y92.192 E1.19571
G1 X60.769 Y92.46 E.012
M73 P95 R0
G1 X87.54 Y119.232 E1.19571
G1 X87.271 Y119.5 E.012
G1 X60.5 Y92.729 E1.19571
G1 X60.231 Y92.997 E.012
M73 P96 R0
G1 X87.003 Y119.769 E1.19571
G1 X86.734 Y120.037 E.012
M73 P97 R0
G1 X59.963 Y93.266 E1.19571
G1 X59.694 Y93.535 E.012
G1 X86.585 Y120.426 E1.20107
M204 P1250
; stop printing object test_sheet_50x40x025 id:0 copy 0
G1 E-2.24 F2700
;WIPE_START
M73 P98 R0
G1 F7200;_WIPE
G1 X84.775 Y118.616 E-.912
;WIPE_END
G1 E-.048 F2700
G1 Z.4 F9000
M107
;TYPE:Custom
; Filament-specific end gcode
G1 E-1 F2100 ; retract
G1 Z2.2 F720 ; Move print head up
G1 X178 Y178 F4200 ; park print head
G1 Z30.2 F720 ; Move print head further up
G4 ; wait
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M221 S100 ; reset flow
M900 K0 ; reset LA
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
; filament used [mm] = 170.47
; filament used [cm3] = 0.41
; filament used [g] = 0.52
; filament cost = 0.02
; total filament used [g] = 0.52
; total filament cost = 0.02
; estimated printing time (normal mode) = 4m 53s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,180x0,180x180,0x180
; bed_temperature = 90
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 50
; bridge_flow_ratio = 0.95
; bridge_speed = 30
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.4";"printer_model==\"MINI\" and nozzle_diameter[0]!=0.8 and nozzle_diameter[0]!=0.6"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1250
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MINI
; deretract_speed = 40
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G1 E-1 F2100 ; retract\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+2, max_print_height)} F720 ; Move print head up{endif}\nG1 X178 Y178 F4200 ; park print head\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM221 S100 ; reset flow\nM900 K0 ; reset LA\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 30
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 35
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 20
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 36.29
; filament_density = 1.27
; filament_deretract_speed = 25
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 7
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = 1
; filament_retract_speed = 45
; filament_settings_id = "Prusament PETG @MINI"
; filament_soluble = 0
; filament_spool_weight = 201
; filament_toolchange_delay = 0
; filament_type = PETG
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Prusa Polymers
; fill_angle = 45
; fill_density = 15%
; fill_pattern = adaptivecubic
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 85
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 240
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin2
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = "0.20mm QUALITY @MINI";;
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000
; machine_max_acceleration_extruding = 1250
; machine_max_acceleration_retracting = 1250
; machine_max_acceleration_travel = 2500
; machine_max_acceleration_x = 2500
; machine_max_acceleration_y = 2500
; machine_max_acceleration_z = 400
; machine_max_feedrate_e = 80
; machine_max_feedrate_x = 180
; machine_max_feedrate_y = 180
; machine_max_feedrate_z = 12
; machine_max_jerk_e = 10
; machine_max_jerk_x = 8
; machine_max_jerk_y = 8
; machine_max_jerk_z = 2
; machine_min_extruding_rate = 0
; machine_min_travel_rate = 0
; max_fan_speed = 50
; max_layer_height = 0.25
; max_print_height = 180
; max_print_speed = 150
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 30
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 40
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MINI - Copy
; printer_model = MINI
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MINI\n
; printer_settings_id = Original Prusa MINI & MINI+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1.5
; retract_before_wipe = 70%
; retract_layer_change = 1
; retract_length = 3.2
; retract_length_toolchange = 4
; retract_lift = 0.2
; retract_lift_above = 0
; retract_lift_below = 179
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 70
; seam_position = nearest
; silent_mode = 0
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if nozzle_diameter[0]==0.6}0.12{elsif nozzle_diameter[0]==0.8}0.06{else}0.2{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S170 ; set extruder temp for bed leveling\nM140 S[first_layer_bed_temperature] ; set bed temp\nM109 R170 ; wait for bed leveling temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM204 T1250 ; set travel acceleration\nG28 ; home all without mesh bed level\nG29 ; mesh bed leveling \nM204 T[machine_max_acceleration_travel] ; restore travel acceleration\nM104 S[first_layer_temperature] ; set extruder temp\nG92 E0\nG1 Y-2 X179 F2400\nG1 Z3 F720\nM109 S[first_layer_temperature] ; wait for extruder temp\n\n; intro line\nG1 X170 F1000\nG1 Z0.2 F720\nG1 X110 E8 F900\nG1 X40 E10 F700\nG92 E0\n\nM221 S95 ; set flow
; support_material = 1
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.1
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 40
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 55
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 250
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; threads = 12
; thumbnails = 16x16,220x124
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_speed = 150
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 140
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
